import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, FlaskConical, Play, Square, Trash2, X } from 'lucide-react';
import type { UserProfile } from '../../types';
import { REVIEW_STORAGE_KEY, REVIEW_TASKS_CHANGED, WORKSTATIONS, createNonOutputScenario, createOutputScenario, getTaskMetrics, getTaskStatus, loadReviewTasks, saveReviewTasks, type ReviewCompletionStatus, type ReviewParticipant, type ReviewTask, type ReviewTaskType } from '../../lib/reviewTasks';

const clean = (v: string) => v.split(' / ')[0];
const num = (v: number) => v.toLocaleString(undefined, { maximumFractionDigits: 1 });
const clock = () => new Date().toLocaleTimeString('en-SG', { hour: '2-digit', minute: '2-digit', hour12: false });
const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };

export const ReviewBanner = () => <div className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-3 text-center text-sm font-bold text-amber-900"><FlaskConical className="mr-2 inline h-4 w-4"/>OT PRO V1.3 REVIEW MODE <span className="mx-2">•</span> NO PRODUCTION DATA WILL BE SAVED</div>;

function useTasks() {
  const [tasks,setTasks] = useState<ReviewTask[]>(loadReviewTasks);
  useEffect(() => { const refresh=()=>setTasks(loadReviewTasks()); window.addEventListener(REVIEW_TASKS_CHANGED,refresh); window.addEventListener('storage',refresh); return ()=>{window.removeEventListener(REVIEW_TASKS_CHANGED,refresh);window.removeEventListener('storage',refresh)}; },[]);
  const update=(fn:(t:ReviewTask[])=>ReviewTask[])=>setTasks(current=>{const next=fn(current);saveReviewTasks(next);return next});
  return {tasks,update};
}

export function ReviewSupervisorTasks({employees}:{employees:UserProfile[]}) {
  const {tasks,update}=useTasks(); const [creating,setCreating]=useState(false); const [closing,setClosing]=useState<ReviewTask|null>(null);
  const available=employees.filter(e=>e.role==='employee');
  const close=(id:string,result:string,status:ReviewCompletionStatus,note:string)=>update(all=>all.map(t=>t.id===id?{...t,actualResult:result,completionStatus:status,supervisorNote:note,status:'CLOSED',closedAt:new Date().toISOString()}:t));
  return <section className="space-y-4 no-print"><ReviewBanner/><div className="rounded-3xl border border-indigo-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">Supervisor-owned review workflow</p><h2 className="text-2xl font-black">OT TASKS / 加班任务</h2></div><div className="flex gap-2"><button disabled={available.length<4} onClick={()=>update(all=>[createOutputScenario(available),createNonOutputScenario(available),...all])} className="rounded-xl border px-3 py-2 text-xs font-bold disabled:opacity-40">LOAD TEST SCENARIOS</button><button onClick={()=>setCreating(true)} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white">CREATE OT TASK</button></div></div>
    {!tasks.length?<p className="mt-5 rounded-2xl border border-dashed p-7 text-center text-sm text-slate-500">No review tasks yet. Browser review storage only.</p>:<div className="mt-5 grid gap-4">{tasks.map(t=>{const m=getTaskMetrics(t);return <article key={t.id} className="rounded-2xl border p-5"><div className="flex justify-between gap-2"><div><p className="text-xs font-bold text-indigo-600">{t.date} · {t.plannedStart}–{t.plannedEnd}</p><h3 className="text-xl font-black">{clean(t.workstation)}</h3><p className="text-sm text-slate-500">{t.product||'Non-output work'}{t.batchNo?` · ${t.batchNo}`:''}</p></div><span className="h-fit rounded-full bg-slate-900 px-3 py-1 text-[10px] font-black text-white">{getTaskStatus(t)}</span></div><p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><strong>Requirement:</strong> {t.targetRequirement}</p><div className="mt-3 grid grid-cols-3 gap-2"><Metric l="Employees" v={`${t.participants.length}`}/><Metric l="Man-hours" v={`${m.totalManHours.toFixed(1)}h`}/><Metric l="Productivity" v={m.productivity===null?'N/A':`${num(m.productivity)} / hr`}/></div>{t.actualResult&&<p className="mt-3 text-sm"><strong>Actual:</strong> {t.actualResult} · <strong>{t.completionStatus}</strong></p>}<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="text-slate-400"><tr><th className="p-2">Employee</th><th>Confirmed</th><th>Start</th><th>End</th><th>Actual Hours</th><th>Assigned Workstation</th><th>Actual Workstation</th><th>Status</th></tr></thead><tbody>{t.participants.map(p=><tr key={p.employeeId} className="border-t"><td className="p-2 font-bold">{p.employeeName}</td><td>{p.status==='NOT STARTED'?'NO':'YES'}</td><td>{p.startTime||'—'}</td><td>{p.endTime||'—'}</td><td>{p.actualHours.toFixed(1)}h</td><td>{clean(p.assignedWorkstation)}</td><td>{clean(p.actualWorkstation)}</td><td>{p.actualWorkstation!==p.assignedWorkstation?'WORK CHANGED':p.status==='NOT STARTED'?'NOT CONFIRMED':p.status}</td></tr>)}</tbody></table></div>{t.status!=='CLOSED'&&t.status!=='CANCELLED'&&<div className="mt-4 flex gap-2"><button onClick={()=>setClosing(t)} className="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">CLOSE TASK</button><button onClick={()=>update(all=>all.map(x=>x.id===t.id?{...x,status:'CANCELLED'}:x))} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">CANCEL</button></div>}</article>})}</div>}</div>
    {creating&&<CreateTask employees={available} dismiss={()=>setCreating(false)} create={t=>{update(all=>[t,...all]);setCreating(false)}}/>}{closing&&<CloseTask task={closing} dismiss={()=>setClosing(null)} close={(r,s,n)=>{close(closing.id,r,s,n);setClosing(null)}}/>}
  </section>;
}

function CreateTask({employees,dismiss,create}:{employees:UserProfile[];dismiss:()=>void;create:(t:ReviewTask)=>void}) {
  const [type,setType]=useState<ReviewTaskType>('output'); const [selected,setSelected]=useState<string[]>([]); const [search,setSearch]=useState('');
  const [f,setF]=useState({date:localDate(),department:'Production',workstation:WORKSTATIONS[7],product:'',batchNo:'',plannedStart:'18:00',plannedEnd:'21:00',targetRequirement:''});
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!selected.length)return;create({id:`review-${Date.now()}`,...f,taskType:type,status:'PLANNED',createdAt:new Date().toISOString(),participants:employees.filter(x=>selected.includes(x.id)).map(x=>({employeeId:x.id,employeeName:x.name,status:'NOT STARTED',assignedWorkstation:f.workstation,actualWorkstation:f.workstation,actualHours:0}))})};
  return <Modal title="CREATE REVIEW OT TASK" close={dismiss}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field l="Date / 日期"><input required type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field l="Department / 部门"><input required value={f.department} onChange={e=>setF({...f,department:e.target.value})}/></Field><Field l="Workstation / 工位"><select value={f.workstation} onChange={e=>setF({...f,workstation:e.target.value})}>{WORKSTATIONS.map(w=><option key={w}>{w}</option>)}</select></Field><Field l="Task Type"><select value={type} onChange={e=>setType(e.target.value as ReviewTaskType)}><option value="output">OUTPUT TASK</option><option value="non-output">NON-OUTPUT TASK</option></select></Field><Field l="Product / 产品 (optional)"><input value={f.product} onChange={e=>setF({...f,product:e.target.value})}/></Field><Field l="Batch No. / 批号 (optional)"><input value={f.batchNo} onChange={e=>setF({...f,batchNo:e.target.value})}/></Field><Field l="Planned Start"><input required type="time" value={f.plannedStart} onChange={e=>setF({...f,plannedStart:e.target.value})}/></Field><Field l="Planned End"><input required type="time" value={f.plannedEnd} onChange={e=>setF({...f,plannedEnd:e.target.value})}/></Field><div className="sm:col-span-2"><Field l="Target / Task Requirement / 目标或任务要求"><textarea required rows={3} value={f.targetRequirement} onChange={e=>setF({...f,targetRequirement:e.target.value})}/></Field></div><div className="sm:col-span-2"><p className="text-sm font-bold">Actual employees / 实际员工</p><input aria-label="Search employees" placeholder="Search employees" value={search} onChange={e=>setSearch(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/><div className="my-2 flex gap-3"><button type="button" onClick={()=>setSelected(employees.map(x=>x.id))} className="text-xs font-bold text-indigo-700">SELECT ALL</button><button type="button" onClick={()=>setSelected([])} className="text-xs font-bold">CLEAR</button></div><div className="max-h-52 overflow-auto rounded-xl border p-2">{employees.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).map(x=><label key={x.id} className="flex gap-2 rounded p-2 text-sm hover:bg-slate-50"><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>setSelected(a=>a.includes(x.id)?a.filter(id=>id!==x.id):[...a,x.id])}/>{x.name}<span className="ml-auto text-slate-400">{x.department}</span></label>)}</div></div><button disabled={!selected.length} className="min-h-12 rounded-xl bg-indigo-600 font-black text-white disabled:opacity-40 sm:col-span-2">CREATE REVIEW TASK ({selected.length})</button></form></Modal>;
}

function CloseTask({task,dismiss,close}:{task:ReviewTask;dismiss:()=>void;close:(r:string,s:ReviewCompletionStatus,n:string)=>void}) { const [r,setR]=useState('');const [s,setS]=useState<ReviewCompletionStatus>('COMPLETED');const [n,setN]=useState('');return <Modal title={`CLOSE ${clean(task.workstation)} TASK`} close={dismiss}><div className="space-y-4"><Field l="Actual Result / 实际结果"><textarea rows={4} value={r} onChange={e=>setR(e.target.value)}/></Field><Field l="Completion Status / 完成状态"><select value={s} onChange={e=>setS(e.target.value as ReviewCompletionStatus)}><option>COMPLETED</option><option>PARTIALLY COMPLETED</option><option>NOT COMPLETED</option></select></Field><Field l="Supervisor Note / 主管备注 (private)"><textarea rows={3} value={n} onChange={e=>setN(e.target.value)}/></Field><button disabled={!r.trim()} onClick={()=>close(r.trim(),s,n.trim())} className="w-full rounded-xl bg-indigo-600 p-3 font-black text-white disabled:opacity-40">CLOSE OT TASK</button></div></Modal> }

export function ReviewEmployeeAssignments({employee}:{employee:UserProfile}) {
  const {tasks,update}=useTasks(); const list=useMemo(()=>tasks.filter(t=>t.status!=='CANCELLED'&&t.date===localDate()&&t.participants.some(p=>p.employeeId===employee.id)).sort((a,b)=>a.plannedStart.localeCompare(b.plannedStart)),[tasks,employee.id]);
  const change=(id:string,fn:(p:ReviewParticipant)=>ReviewParticipant)=>update(all=>all.map(t=>t.id===id?{...t,participants:t.participants.map(p=>p.employeeId===employee.id?fn(p):p)}:t));
  return <section className="space-y-3 no-print"><ReviewBanner/><div><h2 className="text-xl font-black">TONIGHT'S OT ASSIGNMENT</h2><p className="text-sm text-slate-500">今晚加班安排 · review actions require no login</p></div>{!list.length&&<div className="rounded-2xl border bg-white p-5 text-center text-sm text-slate-500">No OT assignment for tonight.<br/>今晚没有加班安排。</div>}{list.map(t=>{const p=t.participants.find(x=>x.employeeId===employee.id)!;return <article key={t.id} className="rounded-3xl border border-indigo-200 bg-white p-5"><p className="text-xs font-bold text-indigo-600">{t.plannedStart}–{t.plannedEnd} · {t.department}</p><h3 className="text-2xl font-black">{clean(t.workstation)}</h3>{t.product&&<p className="font-bold">{t.product}{t.batchNo?` · ${t.batchNo}`:''}</p>}<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><strong>Task:</strong> {t.targetRequirement}</p>{t.status==='CLOSED'&&t.actualResult?<p className="mt-3 text-sm"><strong>Result:</strong> {t.actualResult} · {t.completionStatus}</p>:<Actions p={p} update={fn=>change(t.id,fn)}/>}</article>})}</section>;
}

function Actions({p,update}:{p:ReviewParticipant;update:(fn:(p:ReviewParticipant)=>ReviewParticipant)=>void}) { const [changed,setChanged]=useState(false);if(p.status==='COMPLETED')return <p className="mt-4 rounded-xl bg-emerald-50 p-4 text-center font-black text-emerald-800"><CheckCircle2 className="mr-2 inline h-5 w-5"/>OT COMPLETED · {p.actualHours.toFixed(1)}h</p>;if(p.status==='OT IN PROGRESS')return <div className="mt-4 space-y-3"><p className="rounded-xl bg-emerald-50 p-3 text-center font-bold">OT IN PROGRESS · {p.startTime}</p><div className="grid grid-cols-3 gap-2">{[1,2,3].map(h=><button key={h} onClick={()=>update(x=>({...x,actualHours:h}))} className="rounded-xl bg-amber-50 py-3 font-bold">{h} hr</button>)}</div><button disabled={!p.actualHours} onClick={()=>update(x=>({...x,status:'COMPLETED',endTime:clock()}))} className="min-h-14 w-full rounded-xl bg-slate-900 font-black text-white disabled:opacity-40"><Square className="mr-2 inline h-5 w-5"/>END OT</button></div>;if(p.status==='CONFIRMED')return <button onClick={()=>update(x=>({...x,status:'OT IN PROGRESS',startTime:clock()}))} className="mt-4 min-h-14 w-full rounded-xl bg-emerald-600 font-black text-white"><Play className="mr-2 inline h-5 w-5"/>START OT</button>;return <div className="mt-4 space-y-2"><button onClick={()=>update(x=>({...x,status:'CONFIRMED'}))} className="min-h-14 w-full rounded-xl bg-indigo-600 font-black text-white">CONFIRM ASSIGNMENT</button><button onClick={()=>setChanged(!changed)} className="min-h-12 w-full rounded-xl border-2 font-bold">WORK CHANGED</button>{changed&&<select aria-label="Actual workstation" defaultValue="" onChange={e=>update(x=>({...x,status:'CONFIRMED',actualWorkstation:e.target.value}))} className="w-full rounded-xl border p-3"><option value="" disabled>Select actual workstation</option>{WORKSTATIONS.map(w=><option key={w}>{w}</option>)}</select>}</div> }

export function ReviewManagerAnalysis() { const {tasks,update}=useTasks();const [reset,setReset]=useState('');const rows=tasks.filter(t=>t.status==='CLOSED');return <div className="space-y-5"><ReviewBanner/><div><p className="text-xs font-bold uppercase text-indigo-600">Manager review analytics</p><h2 className="text-3xl font-black">OT TASK ANALYSIS</h2></div><div className="overflow-x-auto rounded-3xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-white"><tr><th className="p-4">Task</th><th>Employees</th><th>Man-hours</th><th>Completion</th><th>Requirement</th><th>Actual</th><th>Productivity</th></tr></thead><tbody>{rows.map(t=>{const m=getTaskMetrics(t);return <tr key={t.id} className="border-t"><td className="p-4 font-black">{clean(t.workstation)}<span className="block text-xs font-normal text-slate-400">{t.date}</span></td><td>{t.participants.length}</td><td>{m.totalManHours.toFixed(1)}h</td><td>{t.completionStatus||'N/A'}</td><td>{t.targetRequirement}</td><td>{t.actualResult||'N/A'}</td><td>{m.productivity===null?'N/A':`${num(m.productivity)} / hr`}</td></tr>})}</tbody></table>{!rows.length&&<p className="p-8 text-center text-slate-500">No closed review tasks.</p>}</div><section className="rounded-2xl border border-amber-200 bg-white p-5"><h3 className="font-black">RESET REVIEW DATA</h3><p className="text-xs text-slate-500">Only clears {REVIEW_STORAGE_KEY}. Firestore is never contacted.</p><div className="mt-3 flex gap-2"><input value={reset} onChange={e=>setReset(e.target.value)} placeholder="Type RESET REVIEW DATA" className="min-w-0 flex-1 rounded-xl border p-3"/><button disabled={reset!=='RESET REVIEW DATA'} onClick={()=>{localStorage.removeItem(REVIEW_STORAGE_KEY);update(()=>[]);setReset('')}} className="rounded-xl bg-red-700 px-4 font-bold text-white disabled:opacity-30"><Trash2 className="mr-2 inline h-4 w-4"/>RESET</button></div></section></div> }

const Metric=({l,v}:{l:string;v:string})=><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">{l}</p><p className="font-black">{v}</p></div>;
const Field=({l,children}:{l:string;children:React.ReactNode})=><label className="block text-sm font-bold">{l}<div className="mt-1 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:p-3">{children}</div></label>;
const Modal=({title,close,children}:{title:string;close:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><h2 className="text-xl font-black">{title}</h2><button aria-label="Close" onClick={close} className="rounded-xl bg-slate-100 p-2"><X className="h-5 w-5"/></button></div><div className="p-5">{children}</div></div></div>;
