import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Briefcase, CheckCircle2, FlaskConical, Play, Square, Trash2, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { REVIEW_EMPLOYEES, REVIEW_STORAGE_KEY, WORKSTATIONS, createScenarioTask, getTaskMetrics, getTaskStatus, loadReviewTasks, saveReviewTasks, type ReviewParticipant, type ReviewTask, type ReviewTaskType } from './lib/reviewTasks';

type View = 'supervisor' | 'employee' | 'manager';
const cleanWorkstation = (value: string) => value.split(' / ')[0];
const nowTime = () => new Date().toLocaleTimeString('en-SG', { hour: '2-digit', minute: '2-digit', hour12: false });
const number = (value: number) => value.toLocaleString(undefined, { maximumFractionDigits: 1 });

const Banner = () => <div className="border-b border-amber-200 bg-amber-50 px-5 py-3 text-center text-sm font-bold text-amber-900"><FlaskConical className="mr-2 inline h-4 w-4"/> OT PRO V1.3 REVIEW MODE <span className="mx-2 text-amber-400">•</span> NO PRODUCTION DATA WILL BE SAVED</div>;

export default function ReviewLab() {
  const navigate = useNavigate();
  const [view, setView] = useState<View>('supervisor');
  const [tasks, setTasks] = useState<ReviewTask[]>(loadReviewTasks);
  const [selectedEmployee, setSelectedEmployee] = useState(REVIEW_EMPLOYEES[0].id);
  const [detailTask, setDetailTask] = useState<ReviewTask | null>(null);
  const [workstationDetail, setWorkstationDetail] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [resetText, setResetText] = useState('');

  useEffect(() => { saveReviewTasks(tasks); }, [tasks]);
  const updateTask = (taskId: string, updater: (task: ReviewTask) => ReviewTask) => setTasks((current) => current.map((task) => task.id === taskId ? updater(task) : task));
  const updateParticipant = (taskId: string, employeeId: string, updater: (participant: ReviewParticipant) => ReviewParticipant) => updateTask(taskId, (task) => ({ ...task, participants: task.participants.map((participant) => participant.employeeId === employeeId ? updater(participant) : participant) }));
  const employeeTasks = tasks.filter((task) => task.status !== 'CANCELLED' && task.participants.some((participant) => participant.employeeId === selectedEmployee));

  return <div className="min-h-screen bg-slate-50 text-slate-900"><Banner/><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 px-4 py-4 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><button onClick={() => navigate('/portal')} className="rounded-xl bg-slate-100 p-2 hover:bg-slate-200" aria-label="Back to manager portal"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="text-xl font-black">OT Task Workflow Review</h1><p className="text-xs text-slate-500">加班任务流程实验功能</p></div></div><nav className="flex rounded-xl bg-slate-100 p-1">{(['supervisor','employee','manager'] as View[]).map((item)=><button key={item} onClick={()=>setView(item)} className={`flex-1 rounded-lg px-4 py-2 text-xs font-black uppercase ${view===item?'bg-slate-900 text-white shadow':'text-slate-600 hover:bg-white'}`}>{item}</button>)}</nav></div></header>
    <main className="mx-auto max-w-7xl p-4 sm:p-8">{view === 'supervisor' ? <SupervisorView tasks={tasks} onCreate={()=>setShowCreate(true)} onScenario={()=>setTasks((current)=>[createScenarioTask(),...current])} onUpdate={updateTask} onDetail={setDetailTask}/> : view === 'employee' ? <EmployeeView tasks={employeeTasks} employeeId={selectedEmployee} onEmployee={setSelectedEmployee} onParticipant={updateParticipant}/> : <ManagerView tasks={tasks} onTask={setDetailTask} onWorkstation={setWorkstationDetail}/>}</main>
    <div className="mx-auto max-w-7xl px-4 pb-10 sm:px-8"><section className="rounded-2xl border border-amber-200 bg-white p-5"><h2 className="font-black text-slate-900">RESET REVIEW DATA</h2><p className="mt-1 text-xs text-slate-500">Only clears local key: {REVIEW_STORAGE_KEY}. Firestore is never contacted.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={resetText} onChange={(event)=>setResetText(event.target.value)} placeholder="Type RESET REVIEW DATA" className="rounded-xl border border-slate-200 px-4 py-2 text-sm"/><button disabled={resetText !== 'RESET REVIEW DATA'} onClick={()=>{localStorage.removeItem(REVIEW_STORAGE_KEY);setTasks([]);setResetText('')}} className="rounded-xl bg-red-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-30"><Trash2 className="mr-2 inline h-4 w-4"/>RESET REVIEW DATA</button></div></section></div>
    {showCreate && <CreateTaskModal onClose={()=>setShowCreate(false)} onCreate={(task)=>{setTasks((current)=>[task,...current]);setShowCreate(false)}}/>}
    {detailTask && <TaskDetail task={tasks.find((task)=>task.id===detailTask.id) || detailTask} onClose={()=>setDetailTask(null)}/>}
    {workstationDetail && <WorkstationDetail workstation={workstationDetail} tasks={tasks} onTask={setDetailTask} onClose={()=>setWorkstationDetail(null)}/>}
  </div>;
}

function SupervisorView({ tasks, onCreate, onScenario, onUpdate, onDetail }: { tasks: ReviewTask[]; onCreate:()=>void; onScenario:()=>void; onUpdate:(id:string,fn:(task:ReviewTask)=>ReviewTask)=>void; onDetail:(task:ReviewTask)=>void }) {
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Supervisor Review</p><h2 className="text-3xl font-black">OT TASKS <span className="text-lg font-medium text-slate-400">/ 加班任务</span></h2></div><div className="flex gap-2"><button onClick={onScenario} className="rounded-xl border border-indigo-200 bg-white px-4 py-3 text-sm font-bold text-indigo-700">LOAD TEST SCENARIO</button><button onClick={onCreate} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">CREATE OT TASK</button></div></div>
    {!tasks.length && <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><Briefcase className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-3 font-bold">No review tasks yet</p><p className="text-sm text-slate-500">Create a task or load the required test scenario.</p></div>}
    <div className="grid gap-5 lg:grid-cols-2">{tasks.map((task)=>{const metrics=getTaskMetrics(task);const started=task.participants.filter((p)=>p.status!=='NOT STARTED'&&p.status!=='CONFIRMED').length;const completed=task.participants.filter((p)=>p.status==='COMPLETED').length;const changed=task.participants.filter((p)=>p.actualWorkstation!==p.assignedWorkstation).length;return <article key={task.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-indigo-600">{task.date}</p><h3 className="mt-1 text-2xl font-black uppercase">{cleanWorkstation(task.workstation)}</h3><p className="text-sm text-slate-600">{task.product || 'Non-output work'} · {task.batchNo || 'No batch'}</p></div><span className="rounded-full bg-slate-900 px-3 py-1 text-xs font-black text-white">{getTaskStatus(task)}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Metric label="Planned" value={`${task.plannedStart}–${task.plannedEnd}`}/><Metric label="Employees" value={`${task.participants.length}`}/><Metric label="Completed" value={`${completed}`}/><Metric label="Man-hours" value={`${metrics.totalManHours.toFixed(1)}h`}/></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-slate-600"><span>{started} Started</span><span>•</span><span>{completed} Completed</span><span>•</span><span>{changed} Work Changed</span></div>{task.taskType==='output'&&<p className="mt-4 rounded-xl bg-indigo-50 p-3 text-sm"><strong>Target:</strong> {number(task.targetOutput)} {task.outputUnit}</p>}
      <div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>onDetail(task)} className="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white">VIEW</button>{task.status!=='CLOSED'&&task.status!=='CANCELLED'&&<><CloseTask task={task} onClose={(actualOutput,note)=>onUpdate(task.id,(current)=>({...current,status:'CLOSED',actualOutput,supervisorNote:note,closedAt:new Date().toISOString()}))}/><button onClick={()=>onUpdate(task.id,(current)=>({...current,status:'CANCELLED'}))} className="rounded-lg bg-red-50 px-4 py-2 text-xs font-bold text-red-700">CANCEL REVIEW TASK</button></>}</div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="text-slate-400"><tr><th className="py-2">Employee</th><th>Status</th><th>Actual Workstation</th></tr></thead><tbody>{task.participants.map((p)=><tr key={p.employeeId} className="border-t border-slate-100"><td className="py-2 font-bold">{p.employeeName}</td><td>{p.status}</td><td>{cleanWorkstation(p.actualWorkstation)}{p.actualWorkstation!==p.assignedWorkstation&&<span className="ml-2 text-amber-700">CHANGED</span>}</td></tr>)}</tbody></table></div></article>})}</div>
  </div>;
}

function EmployeeView({ tasks, employeeId, onEmployee, onParticipant }: { tasks: ReviewTask[]; employeeId:string; onEmployee:(id:string)=>void; onParticipant:(taskId:string,employeeId:string,fn:(p:ReviewParticipant)=>ReviewParticipant)=>void }) {
  return <div className="mx-auto max-w-xl space-y-5"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Employee Review · Mobile Flow</p><h2 className="text-3xl font-black">TONIGHT'S OT ASSIGNMENT</h2><p className="text-slate-500">今晚加班安排</p><select aria-label="Review employee" value={employeeId} onChange={(e)=>onEmployee(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 bg-white p-3 font-bold">{REVIEW_EMPLOYEES.map((employee)=><option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></div>
    {!tasks.length&&<div className="rounded-3xl bg-white p-8 text-center shadow-sm"><p className="font-bold">No assignment for this review employee.</p></div>}
    {tasks.map((task)=>{const p=task.participants.find((item)=>item.employeeId===employeeId)!;return <article key={task.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-3xl font-black uppercase">{cleanWorkstation(task.workstation)}</h3><p className="mt-2 text-lg font-bold">{task.product}</p><p className="text-sm text-slate-500">Batch {task.batchNo}</p><p className="mt-4 text-xl font-black">{task.plannedStart} – {task.plannedEnd}</p>{p.actualWorkstation!==p.assignedWorkstation&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm"><p>Assignment: <strong>{cleanWorkstation(p.assignedWorkstation)}</strong></p><p>Actual: <strong>{cleanWorkstation(p.actualWorkstation)}</strong></p></div>}
      {p.status==='NOT STARTED'&&<div className="mt-6 space-y-3"><p className="text-center font-bold">Is this your actual OT work?</p><button onClick={()=>onParticipant(task.id,employeeId,(current)=>({...current,status:'CONFIRMED'}))} className="min-h-14 w-full rounded-2xl bg-indigo-600 text-base font-black text-white"><CheckCircle2 className="mr-2 inline h-5 w-5"/>CONFIRM ASSIGNMENT</button><WorkChanged onChange={(workstation)=>onParticipant(task.id,employeeId,(current)=>({...current,status:'CONFIRMED',actualWorkstation:workstation}))}/></div>}
      {p.status==='CONFIRMED'&&<button onClick={()=>onParticipant(task.id,employeeId,(current)=>({...current,status:'OT IN PROGRESS',startTime:nowTime()}))} className="mt-6 min-h-16 w-full rounded-2xl bg-emerald-600 text-lg font-black text-white"><Play className="mr-2 inline h-6 w-6"/>START OT</button>}
      {p.status==='OT IN PROGRESS'&&<div className="mt-6 space-y-4"><div className="rounded-2xl bg-emerald-50 p-5 text-center"><p className="text-xs font-black tracking-wider text-emerald-700">OT IN PROGRESS</p><p className="mt-2 text-3xl font-black">{p.actualHours.toFixed(1)}h</p><p className="text-xs text-slate-500">Started {p.startTime}</p></div><div className="rounded-xl border border-dashed border-amber-300 p-4"><p className="mb-3 text-center text-xs font-black text-amber-800">REVIEW SIMULATION ONLY</p><div className="grid grid-cols-3 gap-2">{[1,2,3].map((hours)=><button key={hours} onClick={()=>onParticipant(task.id,employeeId,(current)=>({...current,actualHours:hours}))} className="rounded-xl bg-amber-50 py-3 font-black text-amber-900">+{hours} hr</button>)}</div><button onClick={()=>onParticipant(task.id,employeeId,(current)=>({...current,actualHours:2.5}))} className="mt-2 w-full rounded-xl bg-amber-50 py-2 text-sm font-bold text-amber-900">SET 2.5 hr</button></div><button disabled={!p.actualHours} onClick={()=>onParticipant(task.id,employeeId,(current)=>({...current,status:'COMPLETED',endTime:nowTime()}))} className="min-h-16 w-full rounded-2xl bg-slate-900 text-lg font-black text-white disabled:opacity-30"><Square className="mr-2 inline h-5 w-5"/>END OT</button></div>}
      {p.status==='COMPLETED'&&<div className="mt-6 rounded-2xl bg-indigo-50 p-6 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-indigo-600"/><p className="mt-2 font-black">OT COMPLETED</p><p className="text-3xl font-black text-indigo-700">{p.actualHours.toFixed(1)}h</p></div>}
    </article>})}</div>;
}

function ManagerView({ tasks, onTask, onWorkstation }: { tasks:ReviewTask[]; onTask:(task:ReviewTask)=>void; onWorkstation:(workstation:string)=>void }) {
  const rows=useMemo(()=>{const map=new Map<string,{tasks:ReviewTask[];employees:Set<string>;hours:number;output:number}>();tasks.filter((t)=>t.status==='CLOSED').forEach((task)=>{const row=map.get(task.workstation)??{tasks:[],employees:new Set(),hours:0,output:0};const metrics=getTaskMetrics(task);row.tasks.push(task);task.participants.forEach((p)=>row.employees.add(p.employeeId));row.hours+=metrics.totalManHours;row.output+=task.actualOutput||0;map.set(task.workstation,row)});return [...map.entries()].sort((a,b)=>b[1].hours-a[1].hours)},[tasks]);
  const sample=[{station:'Sacheting',currentHours:240,previousHours:196,currentOutput:48000,previousOutput:46000},{station:'Packing',currentHours:126,previousHours:118,currentOutput:27500,previousOutput:26400}];
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Manager Review</p><h2 className="text-3xl font-black">WORKSTATION OT ANALYSIS</h2><p className="text-slate-500">工位加班分析 · Review data only</p></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-white"><tr><th className="p-4">Workstation</th><th>OT Tasks</th><th>Employees</th><th>OT Man-Hours</th><th>Output</th><th>Output / OT Hr</th></tr></thead><tbody>{rows.map(([station,row])=><tr key={station} onClick={()=>onWorkstation(station)} className="cursor-pointer border-t border-slate-100 hover:bg-indigo-50"><td className="p-4 font-black">{cleanWorkstation(station)}</td><td>{row.tasks.length}</td><td>{row.employees.size}</td><td>{row.hours.toFixed(1)}h</td><td>{number(row.output)}</td><td>{row.hours?number(row.output/row.hours):'—'} / hr</td></tr>)}</tbody></table></div></div>
    <section className="rounded-3xl border border-indigo-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-indigo-600">REVIEW SAMPLE COMPARISON</p><h3 className="mt-1 text-xl font-black">Month-to-Month Workstation Review</h3><div className="mt-5 grid gap-4 lg:grid-cols-2">{sample.map((row)=>{const otChange=(row.currentHours/row.previousHours-1)*100;const outputChange=(row.currentOutput/row.previousOutput-1)*100;return <div key={row.station} className="rounded-2xl bg-slate-50 p-5"><h4 className="font-black">{row.station}</h4><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><Metric label="OT" value={`${row.currentHours}h vs ${row.previousHours}h (+${otChange.toFixed(0)}%)`}/><Metric label="Output" value={`${number(row.currentOutput)} vs ${number(row.previousOutput)} (+${outputChange.toFixed(0)}%)`}/></div>{otChange-outputChange>=10&&<p className="mt-4 rounded-xl bg-amber-100 p-3 text-sm font-bold text-amber-900">ATTENTION: OT growth is significantly higher than Output growth.</p>}</div>})}</div></section>
    <section><h3 className="mb-3 text-lg font-black">Review Task History</h3><div className="grid gap-3">{tasks.map((task)=><button key={task.id} onClick={()=>onTask(task)} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4 text-left hover:border-indigo-300"><span><strong className="block">{cleanWorkstation(task.workstation)} · {task.product||'Non-output task'}</strong><span className="text-xs text-slate-500">{task.date} · {task.batchNo}</span></span><span className="text-xs font-black">VIEW TASK</span></button>)}</div></section>
  </div>;
}

function CreateTaskModal({onClose,onCreate}:{onClose:()=>void;onCreate:(task:ReviewTask)=>void}) {
  const [type,setType]=useState<ReviewTaskType>('output');const [selected,setSelected]=useState<string[]>([]);const [form,setForm]=useState({date:'2026-09-02',department:'Production',workstation:WORKSTATIONS[7],product:'',batchNo:'',plannedStart:'18:00',plannedEnd:'21:00',targetOutput:'',outputUnit:'sachets'});
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!selected.length)return;onCreate({id:`review-${Date.now()}`,...form,targetOutput:type==='output'?Number(form.targetOutput):0,taskType:type,status:'PLANNED',createdAt:new Date().toISOString(),participants:REVIEW_EMPLOYEES.filter((employee)=>selected.includes(employee.id)).map((employee)=>({employeeId:employee.id,employeeName:employee.name,status:'NOT STARTED',assignedWorkstation:form.workstation,actualWorkstation:form.workstation,actualHours:0}))})};
  return <Modal title="CREATE REVIEW OT TASK" onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Date / 日期"><input required type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})}/></Field><Field label="Department / 部门"><select value={form.department} onChange={(e)=>setForm({...form,department:e.target.value})}><option>Production</option><option>Warehouse</option><option>QA/QC</option><option>Office</option></select></Field><Field label="Workstation / 工位"><select value={form.workstation} onChange={(e)=>setForm({...form,workstation:e.target.value})}>{WORKSTATIONS.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Task Type"><select value={type} onChange={(e)=>setType(e.target.value as ReviewTaskType)}><option value="output">OUTPUT TASK</option><option value="non-output">NON-OUTPUT TASK</option></select></Field>{type==='output'&&<><Field label="Product / 产品"><input required value={form.product} onChange={(e)=>setForm({...form,product:e.target.value})}/></Field><Field label="Batch No. / 批号"><input required value={form.batchNo} onChange={(e)=>setForm({...form,batchNo:e.target.value})}/></Field><Field label="Target Output / 目标产量"><input required type="number" value={form.targetOutput} onChange={(e)=>setForm({...form,targetOutput:e.target.value})}/></Field><Field label="Output Unit / 产量单位"><input required value={form.outputUnit} onChange={(e)=>setForm({...form,outputUnit:e.target.value})}/></Field></>}<Field label="Planned Start"><input required type="time" value={form.plannedStart} onChange={(e)=>setForm({...form,plannedStart:e.target.value})}/></Field><Field label="Planned End"><input required type="time" value={form.plannedEnd} onChange={(e)=>setForm({...form,plannedEnd:e.target.value})}/></Field><div className="sm:col-span-2"><p className="mb-2 text-sm font-bold">Assigned Employees / 安排员工</p><div className="grid grid-cols-2 gap-2">{REVIEW_EMPLOYEES.map((employee)=><label key={employee.id} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" checked={selected.includes(employee.id)} onChange={()=>setSelected((current)=>current.includes(employee.id)?current.filter((id)=>id!==employee.id):[...current,employee.id])}/>{employee.name}</label>)}</div></div><button className="min-h-12 rounded-xl bg-indigo-600 font-black text-white sm:col-span-2">CREATE REVIEW TASK</button></form></Modal>;
}

function WorkChanged({onChange}:{onChange:(workstation:string)=>void}){const [open,setOpen]=useState(false);return <div><button onClick={()=>setOpen(!open)} className="min-h-14 w-full rounded-2xl border-2 border-slate-200 text-base font-black">WORK CHANGED</button>{open&&<select aria-label="Actual workstation" onChange={(e)=>onChange(e.target.value)} defaultValue="" className="mt-3 w-full rounded-xl border border-slate-200 p-4"><option value="" disabled>Select actual workstation</option>{WORKSTATIONS.map((item)=><option key={item}>{item}</option>)}</select>}</div>}

function CloseTask({task,onClose}:{task:ReviewTask;onClose:(output:number|undefined,note:string)=>void}){const [open,setOpen]=useState(false);const [output,setOutput]=useState('');const [note,setNote]=useState('');return <>{<button onClick={()=>setOpen(true)} className="rounded-lg bg-indigo-50 px-4 py-2 text-xs font-bold text-indigo-700">CLOSE TASK</button>}{open&&<Modal title="CLOSE REVIEW OT TASK" onClose={()=>setOpen(false)}>{task.taskType==='output'&&<Field label={`Actual Output / 实际产量 (${task.outputUnit})`}><input type="number" required value={output} onChange={(e)=>setOutput(e.target.value)}/></Field>}<Field label="Supervisor Note / 主管备注"><textarea value={note} onChange={(e)=>setNote(e.target.value)}/></Field><button disabled={task.taskType==='output'&&!output} onClick={()=>onClose(task.taskType==='output'?Number(output):undefined,note)} className="mt-4 w-full rounded-xl bg-indigo-600 p-3 font-black text-white disabled:opacity-30">CLOSE OT TASK</button></Modal>}</>}

function TaskDetail({task,onClose}:{task:ReviewTask;onClose:()=>void}){const m=getTaskMetrics(task);return <Modal title={`${cleanWorkstation(task.workstation)} TASK DETAIL`} onClose={onClose}><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Date" value={task.date}/><Metric label="Department" value={task.department}/><Metric label="Planned Time" value={`${task.plannedStart}–${task.plannedEnd}`}/><Metric label="OT Man-Hours" value={`${m.totalManHours.toFixed(1)}h`}/>{task.taskType==='output'&&<><Metric label="Target" value={`${number(task.targetOutput)} ${task.outputUnit}`}/><Metric label="Actual" value={task.actualOutput===undefined?'—':`${number(task.actualOutput)} ${task.outputUnit}`}/><Metric label="Variance" value={m.outputVariance===null?'—':`${m.outputVariance>=0?'+':''}${number(m.outputVariance)}`}/><Metric label="Output / OT Hr" value={m.productivity===null?'—':`${number(m.productivity)} / hr`}/></>}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr><th className="p-2">Name</th><th>Start</th><th>End</th><th>Hours</th><th>Assigned</th><th>Actual</th><th>Changed</th></tr></thead><tbody>{task.participants.map((p)=><tr key={p.employeeId} className="border-t"><td className="p-2 font-bold">{p.employeeName}</td><td>{p.startTime||'—'}</td><td>{p.endTime||'—'}</td><td>{p.actualHours.toFixed(1)}</td><td>{cleanWorkstation(p.assignedWorkstation)}</td><td>{cleanWorkstation(p.actualWorkstation)}</td><td>{p.assignedWorkstation===p.actualWorkstation?'NO':'YES'}</td></tr>)}</tbody></table></div></Modal>}

function WorkstationDetail({workstation,tasks,onTask,onClose}:{workstation:string;tasks:ReviewTask[];onTask:(task:ReviewTask)=>void;onClose:()=>void}){const relevant=tasks.filter((task)=>task.workstation===workstation);const hours=relevant.reduce((sum,task)=>sum+getTaskMetrics(task).totalManHours,0);const output=relevant.reduce((sum,task)=>sum+(task.actualOutput||0),0);const employees=new Set(relevant.flatMap((task)=>task.participants.map((p)=>p.employeeId)));return <Modal title={`${cleanWorkstation(workstation)} WORKSTATION DETAIL`} onClose={onClose}><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Tasks" value={`${relevant.length}`}/><Metric label="Man-Hours" value={`${hours.toFixed(1)}h`}/><Metric label="Employees" value={`${employees.size}`}/><Metric label="Output" value={number(output)}/><Metric label="Output / OT Hr" value={hours?number(output/hours):'—'}/></div><div className="mt-5 space-y-2">{relevant.map((task)=><button key={task.id} onClick={()=>onTask(task)} className="grid w-full grid-cols-4 rounded-xl border p-3 text-left text-xs"><strong>{task.date}</strong><span>{task.product}</span><span>{task.batchNo}</span><span>{getTaskMetrics(task).totalManHours.toFixed(1)}h</span></button>)}</div></Modal>}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-black text-slate-800">{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold text-slate-700">{label}<div className="mt-1 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-slate-200 [&>*]:p-3 [&>*]:font-medium">{children}</div></label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><h2 className="text-xl font-black">{title}</h2><button aria-label="Close" onClick={onClose} className="rounded-xl bg-slate-100 p-2"><X className="h-5 w-5"/></button></div><div className="p-5">{children}</div></div></div>}

